apiVersion: v1
kind: Pod
metadata:
  name: jx-failure
  namespace: jx-production
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - name: shell
    image: alpine
    resources:
      requests:
        cpu: 50m
        memory: 5Mi  
    args:
      - sh
      - -c
      - while true; do wget -q -O - "http://jx-croc-hunter-java-canary:8080/status"; echo; sleep 10; done
      # - while true; do wget -q -O - "http://jx-croc-hunter-java-canary:8080/delay?wait=5"; echo; sleep 10; done
    stdin: true
    tty: true
